services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_DB: vsdb
      POSTGRES_USER: vscoder
      POSTGRES_PASSWORD: vscoder
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    container_name: db-adminer
    ports:
      - "8080:8080"

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    environment:
      DATABASE_URL: "postgresql://vscoder:vscoder@db:5432/authdb"
    depends_on:
      - db
    ports:
      - "5000:5000"

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    environment:
      DATABASE_URL: "postgresql://vscoder:vscoder@db:5432/userdb"
    depends_on:
      - db
    ports:
      - "5001:5001"

volumes:
  pgdata:
    driver: local
